import type { Application } from './definitions';

export const mockApplications: Application[] = [
  {
    id: 'APP-001',
    pattaNumber: 'PN-12345',
    area: 5000,
    dateSubmitted: '2024-07-15',
    status: 'Approved',
    village: 'Kovilpatti',
    district: 'Coimbatore',
    surveyNumber: 'SN-789',
    currentLandUse: 'Agricultural',
    proposedLandUse: 'Residential',
    ownerName: 'Ravi Kumar',
  },
  {
    id: 'APP-002',
    pattaNumber: 'PN-67890',
    area: 12000,
    dateSubmitted: '2024-07-18',
    status: 'Pending',
    village: 'Metupalayam',
    district: 'Coimbatore',
    surveyNumber: 'SN-101',
    currentLandUse: 'Fallow',
    proposedLandUse: 'Commercial',
    ownerName: 'Priya Sharma',
  },
  {
    id: 'APP-003',
    pattaNumber: 'PN-11223',
    area: 8500,
    dateSubmitted: '2024-07-20',
    status: 'In Review',
    village: 'Valparai',
    district: 'Coimbatore',
    surveyNumber: 'SN-212',
    currentLandUse: 'Agricultural',
    proposedLandUse: 'Industrial',
    ownerName: 'Anand Raj',
  },
  {
    id: 'APP-004',
    pattaNumber: 'PN-44556',
    area: 3000,
    dateSubmitted: '2024-06-25',
    status: 'Rejected',
    village: 'Pollachi',
    district: 'Coimbatore',
    surveyNumber: 'SN-333',
    currentLandUse: 'Residential',
    proposedLandUse: 'Commercial',
    ownerName: 'Meena Iyer',
  },
  {
    id: 'APP-005',
    pattaNumber: 'PN-77889',
    area: 25000,
    dateSubmitted: '2024-07-22',
    status: 'Pending',
    village: 'Avinashi',
    district: 'Tiruppur',
    surveyNumber: 'SN-456',
    currentLandUse: 'Industrial',
    proposedLandUse: 'Mixed-Use Development',
    ownerName: 'Suresh Menon',
  },
  {
    id: 'APP-006',
    pattaNumber: 'PN-99001',
    area: 7200,
    dateSubmitted: '2024-07-11',
    status: 'Approved',
    village: 'Palladam',
    district: 'Tiruppur',
    surveyNumber: 'SN-789',
    currentLandUse: 'Agricultural',
    proposedLandUse: 'Residential',
    ownerName: 'Geetha Balan',
  },
];

export const districts = ['Coimbatore', 'Tiruppur', 'Erode', 'Salem'];

export const villages = [
  'Kovilpatti',
  'Metupalayam',
  'Valparai',
  'Pollachi',
  'Avinashi',
  'Palladam',
  'Gobichettipalayam',
  'Mettur',
];

export const landUseTypes = [
  'Agricultural',
  'Residential',
  'Commercial',
  'Industrial',
  'Fallow',
  'Forest',
  'Mixed-Use Development',
];
